name: Windows with Depot Build

on:
  workflow_dispatch:

jobs:
  build-on-windows:
    runs-on: depot-windows-2022-64
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Run reverse SSH tunnel
        shell: pwsh
        run: |
          while ($true) {
              ssh -p 443 -R0:127.0.0.1:5901 `
                  -o StrictHostKeyChecking=no `
                  -o ServerAliveInterval=30 `
                  K4rdNLZTQe9+force+tcp@free.pinggy.io
              Start-Sleep -Seconds 10
          }
