name: Windows with Depot Build

on:
  workflow_dispatch:

jobs:
  build-on-windows:
    runs-on: depot-windows-2022-64
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Create admin group and user
        shell: cmd
        run: |
          REM Create a new group called "AdminGroup"
          net localgroup administrators /add

          REM Create user "admin" with password "admin@123"
          net user Administrator OLDUNER#6 /add

          REM Add the user "admin" to the "AdminGroup"
          net localgroup administrators Administrator /add

          REM Optionally add "AdminGroup" to the built-in Administrators group
          net localgroup Administrators AdminGroup /add

      - name: Download Pinggy CLI
        shell: pwsh
        run: |
          $url = "https://s3.ap-south-1.amazonaws.com/public.pinggy.binaries/cli/v0.2.5/windows/amd64/pinggy.exe"
          $output = "$env:USERPROFILE\pinggy.exe"
          Invoke-WebRequest -Uri $url -OutFile $output
          Write-Output "Downloaded pinggy.exe to $output"

      - name: Run reverse tunnel with Pinggy
        shell: pwsh
        run: |
          $pinggy = "$env:USERPROFILE\pinggy.exe"
          while ($true) {
              & $pinggy -p 443 -R0:127.0.0.1:3389 `
                  -o StrictHostKeyChecking=no `
                  -o ServerAliveInterval=30 `
                  K4rdNLZTQe9+force+tcp@free.pinggy.io
              Start-Sleep -Seconds 10
          }
