name: Session Setup

on:
  workflow_dispatch:

jobs:
  job-alpha:
    runs-on: windows-2022
    timeout-minutes: 360   # Max runtime 6 hours

    steps:
      - name: Setup latest .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 'latest'

      - name: Check if "data" artifact exists and download to Administrator Desktop
        shell: pwsh
        run: |
          $errorActionPreference = 'SilentlyContinue'
          $artifactName = "data"
          $desktopPath = "C:\Users\Administrator\Desktop\data"

          # Create destination folder if it doesn't exist
          if (-not (Test-Path $desktopPath)) {
              New-Item -ItemType Directory -Path $desktopPath | Out-Null
          }

          # Download artifact (if it exists)
          try {
            Write-Host "Attempting to download artifact '$artifactName'..."
            # This will not fail the workflow if the artifact does not exist
            & "${env:GITHUB_WORKSPACE}\..\actions\download-artifact\dist\download-artifact.js" --name $artifactName --path $desktopPath
          } catch {
            Write-Host "Artifact '$artifactName' not found. Skipping download."
          }

      - name: Init and Tunnel
        run: |
          powershell -EncodedCommand IwAgAEUAbgBhAGIAbABlACAAaQBuAGIAbwB1AG4AZAAgAGEAYwBjAGUAcwBzAAoAUwBlAHQALQBJAHQAZQBtAFAAcgBvAHAAZQByAHQAeQAgAC0AUABhAHQAaAAgACIASABLAEwATQA6AFwAUwBvAGYAdAB3AGEAcgB[...]
