name: Run and Commit Docker Container

on:
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull nhbahi/minecraft-server:latest || true
        continue-on-error: true

      - name: Run container in background
        run: docker run -d --name mc-server nhbahi/minecraft-server:latest
        continue-on-error: true

      - name: Make startup.sh executable
        run: docker exec mc-server chmod +x /startup.sh
        continue-on-error: true

      - name: Run startup.sh inside container
        run: docker exec mc-server /startup.sh
        continue-on-error: true

      - name: Follow container logs
        timeout-minutes: 350  # 5 hours 50 minutes
        run: docker logs -f mc-server
        continue-on-error: true

      - name: Stop container
        run: docker stop mc-server
        continue-on-error: true

      - name: Commit container to image
        run: docker commit mc-server nhbahi/minecraft-server:latest
        continue-on-error: true

      - name: Log in to Docker Hub
        run: echo "dckr_pat_hAtx2lXRMOFVTmzQDbDJ_bYIhxI" | docker login --username nhbahi --password-stdin
        continue-on-error: true

      - name: Push image to Docker Hub
        run: docker push nhbahi/minecraft-server:latest
        continue-on-error: true

      - name: Remove container
        run: docker rm mc-server
        continue-on-error: true
