name: Run PufferPanel and Commit

on:
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Pull PufferPanel Docker image
        run: docker pull nhbahi/pufferpanel:latest || true

      - name: Run PufferPanel container in background
        run: docker run -d -p 8080:8080 --name pufferpanel nhbahi/pufferpanel:latest

      - name: Install and run Pinggy for port forwarding
        run: |
          curl -L -o pinggy https://s3.ap-south-1.amazonaws.com/public.pinggy.binaries/cli/v0.2.5/linux/amd64/pinggy
          chmod +x pinggy
          nohup ./pinggy -p 443 -R0:localhost:8080 -L4300:localhost:4300 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 K4rdNLZTQe9+force@free.pinggy.io &

      - name: Follow PufferPanel logs for 5h 43m
        timeout-minutes: 342
        run: docker logs -f pufferpanel

      - name: Commit container to image
        run: docker commit pufferpanel nhbahi/pufferpanel:latest

      - name: Log in to Docker Hub
        run: echo "dckr_pat_hAtx2lXRMOFVTmzQDbDJ_bYIhxI" | docker login --username nhbahi --password-stdin

      - name: Push image to Docker Hub
        run: docker push nhbahi/pufferpanel:latest

      - name: Stop and remove container
        run: |
          docker stop pufferpanel
          docker rm pufferpanel
