name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current user
        run: |
          whoami
          echo "User profile path: $env:USERPROFILE"
        shell: pwsh

      - name: Try listing Administrator directory
        run: |
          dir C:\Users\Administrator
        shell: pwsh
