name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Admin User
        run: |
          net user administrator OLDUSER#6 /add
          net localgroup administrators administrator /add
          echo User 'administrator' created with administrative privileges.
        shell: cmd

      - name: Create Administrator profile folder
        run: |
          mkdir C:\Users\administrator
          echo "This is a test file" > C:\Users\administrator\test.txt
          echo "Administrator profile folder created with a test file."
        shell: cmd

      - name: List files in Administrator profile
        run: |
          dir C:\Users\administrator
        shell: cmd
